name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Sorting...
      run: isort --check --diff src/ tests/
    - name: Linting...
      run: flake8 --count --show-source --statistics --ignore=E501 src/ tests/
    - name: Testing...
      run: python -m pytest --cov=src --cov-report=term-missing tests/
